import { readFile, writeFile, mkdir } from 'node:fs/promises';
// Subset the UI typefaces and serve them locally. New user names fall back to the system's CJK font.
const source = (
  await Promise.all(
    [
      'src/App.tsx',
      'src/game/GameView.tsx',
      'src/game/supplies.ts',
      'shared/types.ts',
      'server/rooms.ts',
    ].map((p) => readFile(p, 'utf8')),
  )
).join('');
const cjk = [...new Set(source.match(/[\u3000-\u9fff\uff00-\uffef]/g) || [])].sort().join('');
const latin = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).join('') + '°′·×秒';
const requests = [
  { name: 'noto-sc', family: 'Noto Sans SC:wght@400..900', text: cjk },
  { name: 'barlow', family: 'Barlow:wght@400;500;600;700;800', text: latin },
  { name: 'barlow-condensed', family: 'Barlow Condensed:wght@500;600;700;800', text: latin },
];
await mkdir('public/assets/fonts', { recursive: true });
let styles =
  '/* Self-hosted Google Fonts, SIL Open Font License. Generated by scripts/fetch-fonts.mjs. */\n';
for (const request of requests) {
  const url = new URL('https://fonts.googleapis.com/css2');
  url.searchParams.set('family', request.family);
  url.searchParams.set('display', 'swap');
  url.searchParams.set('text', request.text);
  const response = await fetch(url, {
    headers: { 'User-Agent': 'Mozilla/5.0 Chrome/130.0.0.0 Safari/537.36' },
  });
  if (!response.ok) throw new Error(`Font CSS failed: ${response.status}`);
  let css = await response.text();
  let count = 0;
  for (const fontUrl of [...new Set([...css.matchAll(/url\((https:[^)]+)\)/g)].map((m) => m[1]))]) {
    const font = await fetch(fontUrl);
    if (!font.ok) throw new Error('Font download failed');
    const path = `/assets/fonts/${request.name}-${count++}.woff2`;
    await writeFile(`public${path}`, Buffer.from(await font.arrayBuffer()));
    css = css.replaceAll(fontUrl, path);
  }
  styles += css + '\n';
  console.log(`${request.name}: ${count} font files`);
}
await writeFile('public/assets/fonts/fonts.css', styles);
for (const [family, path] of [
  ['Barlow', 'ofl/barlow/OFL.txt'],
  ['Barlow Condensed', 'ofl/barlowcondensed/OFL.txt'],
  ['Noto Sans SC', 'ofl/notosanssc/OFL.txt'],
]) {
  const response = await fetch(`https://raw.githubusercontent.com/google/fonts/main/${path}`);
  if (response.ok)
    await writeFile(
      `public/assets/fonts/${family.replaceAll(' ', '-')}-OFL.txt`,
      await response.text(),
    );
}
console.log('Local UI fonts ready.');
